<Project>
  <PropertyGroup>
    <!-- Release date: update this value for each release (YYYYMMDD). -->
    <ReleaseDate>20260913</ReleaseDate>
    <VersionYear>$([System.String]::Copy('$(ReleaseDate)').Substring(0, 4))</VersionYear>
    <VersionMonth>$([System.Int32]::Parse($([System.String]::Copy('$(ReleaseDate)').Substring(4, 2))))</VersionMonth>
    <VersionDay>$([System.Int32]::Parse($([System.String]::Copy('$(ReleaseDate)').Substring(6, 2))))</VersionDay>
    <Version>$(VersionYear).$(VersionMonth).$(VersionDay)</Version>
    <AssemblyVersion>$(Version).0</AssemblyVersion>
    <FileVersion>$(Version).0</FileVersion>
    <InformationalVersion>ver$(ReleaseDate)</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <Product>DocAssistant</Product>
    <Title>DocAssistant</Title>
  </PropertyGroup>
</Project>
